# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22448ed5384a987d081e0c097efcd7cb7706fa7a509f3a778ab65994b77c4b3d9818912bc66d2e152cb5d40844437ed56a997a018f2a305bf414b3f3bcfca472

test:
  secret_key_base: c65d441740c5d4d99cb8acee3474ed73db94d25292f2a74db1d4579e669425969391424bc6cdc4b92aaf9f024409c4b24f26c94371fa26bdd6e11274d383f677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
